import type { Product, Seller, Review, User } from "./types"

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Elegant Abaya",
    nameAr: "عباية أنيقة",
    description: "Beautiful black abaya with embroidery",
    descriptionAr: "عباية سوداء جميلة مع تطريز",
    price: 45.0,
    category: "fashion",
    image: "/elegant-black-abaya.png",
    sellerId: "2",
    sellerName: "نورة محمد",
    stock: 15,
    featured: true,
    approved: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Luxury Perfume",
    nameAr: "عطر فاخر",
    description: "Premium oriental fragrance",
    descriptionAr: "عطر شرقي فاخر",
    price: 65.0,
    category: "beauty",
    image: "/luxury-perfume-bottle.png",
    sellerId: "2",
    sellerName: "نورة محمد",
    stock: 30,
    featured: true,
    approved: true,
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "3",
    name: "Gold Bracelet",
    nameAr: "سوار ذهبي",
    description: "Handcrafted gold bracelet",
    descriptionAr: "سوار ذهبي مصنوع يدوياً",
    price: 180.0,
    category: "jewelry",
    image: "/gold-bracelet.png",
    sellerId: "2",
    sellerName: "نورة محمد",
    stock: 8,
    featured: false,
    approved: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "4",
    name: "Designer Handbag",
    nameAr: "حقيبة يد مصممة",
    description: "Luxury leather handbag",
    descriptionAr: "حقيبة يد جلدية فاخرة",
    price: 120.0,
    category: "accessories",
    image: "/luxury-handbag.png",
    sellerId: "2",
    sellerName: "نورة محمد",
    stock: 12,
    featured: true,
    approved: true,
    createdAt: new Date("2024-02-10"),
  },
]

export const MOCK_SELLERS: Seller[] = [
  {
    id: "2",
    name: "نورة محمد",
    email: "seller@seydaty.com",
    approved: true,
    totalSales: 6500.0,
    totalProducts: 24,
    joinedAt: new Date("2024-01-01"),
  },
  {
    id: "4",
    name: "ليلى حسن",
    email: "layla@seydaty.com",
    approved: false,
    totalSales: 0,
    totalProducts: 0,
    joinedAt: new Date("2024-03-01"),
  },
]

export const CATEGORIES = [
  { id: "fashion", nameAr: "أزياء", name: "Fashion" },
  { id: "beauty", nameAr: "جمال", name: "Beauty" },
  { id: "jewelry", nameAr: "مجوهرات", name: "Jewelry" },
  { id: "accessories", nameAr: "إكسسوارات", name: "Accessories" },
  { id: "home", nameAr: "منزل", name: "Home" },
]

export const MOCK_REVIEWS: Review[] = [
    {
        id: "1",
        productId: "1",
        userId: "1",
        userName: "فاطمة علي",
        rating: 5,
        comment: "Absolutely beautiful abaya! The quality is amazing.",
        createdAt: new Date("2024-02-01"),
    },
    {
        id: "2",
        productId: "1",
        userId: "2",
        userName: "عائشة أحمد",
        rating: 4,
        comment: "Very elegant and comfortable. I love the embroidery.",
        createdAt: new Date("2024-02-05"),
    },
];

export const MOCK_USERS: User[] = MOCK_SELLERS.map(seller => ({...seller, role: 'seller', createdAt: seller.joinedAt}));
