import type { Product, Seller } from "./types"

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Elegant Abaya",
    nameAr: "عباية أنيقة",
    description: "Beautiful black abaya with embroidery",
    descriptionAr: "عباية سوداء جميلة مع تطريز",
    price: 299,
    category: "fashion",
    image: "/elegant-black-abaya.png",
    sellerId: "2",
    sellerName: "نورة محمد",
    stock: 15,
    featured: true,
    approved: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Luxury Perfume",
    nameAr: "عطر فاخر",
    description: "Premium oriental fragrance",
    descriptionAr: "عطر شرقي فاخر",
    price: 450,
    category: "beauty",
    image: "/luxury-perfume-bottle.png",
    sellerId: "2",
    sellerName: "نورة محمد",
    stock: 30,
    featured: true,
    approved: true,
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "3",
    name: "Gold Bracelet",
    nameAr: "سوار ذهبي",
    description: "Handcrafted gold bracelet",
    descriptionAr: "سوار ذهبي مصنوع يدوياً",
    price: 1200,
    category: "jewelry",
    image: "/gold-bracelet.png",
    sellerId: "2",
    sellerName: "نورة محمد",
    stock: 8,
    featured: false,
    approved: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "4",
    name: "Designer Handbag",
    nameAr: "حقيبة يد مصممة",
    description: "Luxury leather handbag",
    descriptionAr: "حقيبة يد جلدية فاخرة",
    price: 850,
    category: "accessories",
    image: "/luxury-handbag.png",
    sellerId: "2",
    sellerName: "نورة محمد",
    stock: 12,
    featured: true,
    approved: true,
    createdAt: new Date("2024-02-10"),
  },
]

export const MOCK_SELLERS: Seller[] = [
  {
    id: "2",
    name: "نورة محمد",
    email: "seller@seydaty.com",
    approved: true,
    totalSales: 45000,
    totalProducts: 24,
    joinedAt: new Date("2024-01-01"),
  },
  {
    id: "4",
    name: "ليلى حسن",
    email: "layla@seydaty.com",
    approved: false,
    totalSales: 0,
    totalProducts: 0,
    joinedAt: new Date("2024-03-01"),
  },
]

export const CATEGORIES = [
  { id: "fashion", nameAr: "أزياء", name: "Fashion" },
  { id: "beauty", nameAr: "جمال", name: "Beauty" },
  { id: "jewelry", nameAr: "مجوهرات", name: "Jewelry" },
  { id: "accessories", nameAr: "إكسسوارات", name: "Accessories" },
  { id: "home", nameAr: "منزل", name: "Home" },
]
